name: scrub
channels:
  - defaults
dependencies:
  - idna=3.3
  - jmespath=0.10.0
  - packaging=21.3
  - pip=21.2.4
  - python=3.10.4
  - python-dateutil=2.8.2
  - pytz=2021.3
  - tzdata=2022a
  - wheel=0.37.1
  - pip:
    - boto3==1.21.32
    - botocore==1.24.32
    - bottleneck==1.3.4
    - certifi==2022.5.18.1
    - intel-openmp==2021.4.0
    - numexpr==2.8.1
    - numpy==1.22
    - pandas==1.4.2
    - pycparser==2.21
    - pyopenssl==22.0.0
    - pyparsing==3.0.4
    - s3transfer==0.5.0
    - selenium==4.2.0
    - six==1.16.0
    - undetected-chromedriver==3.1.5.post4
    - urllib3==1.26.9
